### ISSUE TITLE
CI Mac issue with resources for Python?

### ISSUE THREAD

**Issue by rosslwheeler** [karpathy/llm.c#242]
@Ricardicus - I've been seeing this for a few days now. Is this a GithHub limitation with the Mac runner? Below is a partial log from the CI run. I was just updating a branch in my fork and saw this again. Figured I'd drop a note in case it's new.
```

2024-04-24T17:47:08.7084440Z Installing collected packages: mpmath, urllib3, typing-extensions, tqdm, sympy, safetensors, regex, pyyaml, packaging, numpy, networkx, MarkupSafe, idna, fsspec, filelock, charset-normalizer, requests, jinja2, torch, tiktoken, huggingface-hub, tokenizers, transformers
2024-04-24T17:47:27.0972560Z Successfully installed MarkupSafe-2.1.5 charset-normalizer-3.3.2 filelock-3.13.4 fsspec-2024.3.1 huggingface-hub-0.22.2 idna-3.7 jinja2-3.1.3 mpmath-1.3.0 networkx-3.3 numpy-1.26.4 packaging-24.0 pyyaml-6.0.1 regex-2024.4.16 requests-2.31.0 safetensors-0.4.3 sympy-1.12 tiktoken-0.6.0 tokenizers-0.19.1 torch-2.3.0 tqdm-4.66.2 transformers-4.40.1 typing-extensions-4.11.0 urllib3-2.2.1
2024-04-24T17:47:27.6409360Z ##[group]Run python prepro_tinyshakespeare.py
2024-04-24T17:47:27.6409790Z [36;1mpython prepro_tinyshakespeare.py[0m
2024-04-24T17:47:27.6618450Z shell: /bin/bash -e {0}
2024-04-24T17:47:27.6618710Z ##[endgroup]
2024-04-24T17:47:29.2269560Z Downloading https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt to data/tiny_shakespeare.txt...
2024-04-24T17:47:29.2283770Z 
2024-04-24T17:47:29.2415120Z data/tiny_shakespeare.txt:   0%|          | 0.00/425k [00:00<?, ?iB/s]
2024-04-24T17:47:29.2420860Z data/tiny_shakespeare.txt: 1.06MiB [00:00, 71.0MiB/s]                 
2024-04-24T17:47:29.3844710Z Saved 32768 tokens to data/tiny_shakespeare_val.bin
2024-04-24T17:47:29.3846440Z Saved 305260 tokens to data/tiny_shakespeare_train.bin
2024-04-24T17:47:29.4256470Z ##[group]Run python train_gpt2.py
2024-04-24T17:47:29.4256780Z [36;1mpython train_gpt2.py[0m
2024-04-24T17:47:29.4309190Z shell: /bin/bash -e {0}
2024-04-24T17:47:29.4320770Z ##[endgroup]
2024-04-24T17:47:45.8952060Z Traceback (most recent call last):
2024-04-24T17:47:45.8952540Z Running pytorch 2.3.0
2024-04-24T17:47:45.8953120Z   File "/Users/runner/work/llm.c/llm.c/train_gpt2.py", line 359, in <module>
2024-04-24T17:47:45.8953980Z using device: mps
2024-04-24T17:47:45.8954270Z wrote gpt2_tokenizer.bin
2024-04-24T17:47:45.8954720Z loading weights from pretrained gpt: gpt2
2024-04-24T17:47:45.8957160Z     model.to(device)
2024-04-24T17:47:45.8958670Z   File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1173, in to
2024-04-24T17:47:45.8962250Z     return self._apply(convert)
2024-04-24T17:47:45.8962810Z            ^^^^^^^^^^^^^^^^^^^^
2024-04-24T17:47:45.8963820Z   File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/torch/nn/modules/module.py", line 779, in _apply
2024-04-24T17:47:45.8964520Z     module._apply(fn)
2024-04-24T17:47:45.8965220Z   File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/torch/nn/modules/module.py", line 779, in _apply
2024-04-24T17:47:45.8966020Z     module._apply(fn)
2024-04-24T17:47:45.8966700Z   File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/torch/nn/modules/module.py", line 804, in _apply
2024-04-24T17:47:45.8967360Z     param_applied = fn(param)
2024-04-24T17:47:45.8967700Z                     ^^^^^^^^^
2024-04-24T17:47:45.8968550Z   File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1159, in convert
2024-04-24T17:47:45.8969270Z     return t.to(
2024-04-24T17:47:45.8969520Z            ^^^^^
2024-04-24T17:47:45.8970760Z RuntimeError: MPS backend out of memory (MPS allocated: 0 bytes, other allocations: 0 bytes, max allowed: 7.93 GB). Tried to allocate 147.24 MB on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).
2024-04-24T17:47:46.2765760Z ##[error]Process completed with exit code 1.
2024-04-24T17:47:46.2877330Z Post job cleanup.
2024-04-24T17:47:46.5168210Z [command]/opt/homebrew/bin/git version
2024-04-24T17:47:46.5407810Z git version 2.44.0
2024-04-24T17:47:46.5435440Z Copying '/Users/runner/.gitconfig' to '/Users/runner/work/_temp/b7f85bb3-1878-47b1-9b6b-bcba51f432d7/.gitconfig'
```

**Comment by Ricardicus** [comment]
Yeah I see them too.. I don't know, maybe the mps does not work in the CI execution. We should probably set the device via the commandline so that it runs on the CPU in the CI.

**Comment by Ricardicus** [comment]
Back when it worked we got this info:

Run python train_gpt2.py
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/torch/backends/mps/__init__.py:22: UserWarning: Skipping device Apple Paravirtual device that does not support Metal 2.0 (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSDevice.mm:101.)
  return torch._C._mps_is_available()
Running pytorch 2.2.2
using device: cpu

So, it ran on CPU back then.. I will try to fix so that it runs on CPU even if mps is available.
Perhaps settable via environment variables, or via defines..

**Comment by Ricardicus** [comment]
PR for it here: https://github.com/karpathy/llm.c/pull/251

**Comment by rosslwheeler** [comment]
@Ricardicus - I have 2 cards - will test https://github.com/karpathy/llm.c/pull/251 out. Thanks.

**Comment by rosslwheeler** [comment]
Working well now...
