### ISSUE TITLE
TypeError: normal_() got an unexpected keyword argument 'generator'

### ISSUE THREAD

**Issue by StarHtimE** [karpathy/llm.c#723]
Traceback (most recent call last):
  File "/root/llm.c/train_gpt2.py", line 663, in <module>
    model = GPT.from_pretrained(args.model)
  File "/root/llm.c/train_gpt2.py", line 210, in from_pretrained
    model = GPT(config)
  File "/root/llm.c/train_gpt2.py", line 147, in __init__
    self.apply(self._init_weights)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 897, in apply
    module.apply(fn)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 897, in apply
    module.apply(fn)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 898, in apply
    fn(self)
  File "/root/llm.c/train_gpt2.py", line 160, in _init_weights
    torch.nn.init.normal_(module.weight, mean=0.0, std=0.02, generator=self.init_rng)
TypeError: normal_() got an unexpected keyword argument 'generator'
![image](https://github.com/user-attachments/assets/19061c18-7464-420e-bbea-1f1283cb2c02)

**Comment by StarHtimE** [comment]
How to solve this issue?
