### ISSUE TITLE
OverflowError: can't convert negative int to unsigned

### ISSUE THREAD

**Issue by goswamig** [karpathy/llm.c#8]
$ python train_gpt2.py
using device: mps
2024-04-08 14:29:47.147256: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
loading weights from pretrained gpt: gpt2
config.json: 100%|████████████████████████████████████████████████████████████| 665/665 [00:00<00:00, 724kB/s]
model.safetensors: 100%|███████████████████████████████████████████████████| 548M/548M [00:41<00:00, 13.2MB/s]
generation_config.json: 100%|█████████████████████████████████████████████████| 124/124 [00:00<00:00, 827kB/s]
loading cached tokens in data/tiny_shakespeare_val.bin
/Users/gautam/llm.c/train_gpt2.py:333: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:212.)
  tokens = torch.from_numpy(tokens)
wrote gpt2_124M.bin
wrote gpt2_124M_debug_state.bin
iteration 0, loss: 5.2700114250183105
iteration 1, loss: 4.059763431549072
iteration 2, loss: 3.3751978874206543
iteration 3, loss: 2.8009214401245117
iteration 4, loss: 2.3155126571655273
iteration 5, loss: 1.8491268157958984
iteration 6, loss: 1.3947665691375732
iteration 7, loss: 0.9993425607681274
iteration 8, loss: 0.6240987777709961
iteration 9, loss: 0.3764863610267639
Traceback (most recent call last):
  File "/Users/gautam/llm.c/train_gpt2.py", line 381, in <module>
    print(decode(y[0].tolist()))
  File "/Users/gautam/llm.c/train_gpt2.py", line 313, in <lambda>
    decode = lambda l: enc.decode(l)
  File "/Users/gautam/miniconda3/lib/python3.10/site-packages/tiktoken/core.py", line 254, in decode
    return self._core_bpe.decode_bytes(tokens).decode("utf-8", errors=errors)
OverflowError: can't convert negative int to unsigned

**Comment by goswamig** [comment]
After upgrading pytorch to 2.2 it worked.

```
wrote gpt2_124M.bin
wrote gpt2_124M_debug_state.bin
iteration 0, loss: 5.2700114250183105
iteration 1, loss: 4.059763431549072
iteration 2, loss: 3.375196933746338
iteration 3, loss: 2.800921678543091
iteration 4, loss: 2.315511703491211
iteration 5, loss: 1.8491261005401611
iteration 6, loss: 1.3947659730911255
iteration 7, loss: 0.999342679977417
iteration 8, loss: 0.6240994930267334
iteration 9, loss: 0.37648487091064453
<|endoftext|>First Citizen:
We are called upon to defend us, the patricians
```
